version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: meetmit
      POSTGRES_PASSWORD: meetmit
      POSTGRES_DB: meetmit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://meetmit:meetmit@db:5432/meetmit?schema=public"
      API_SECRET: "dev-secret"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
    depends_on:
      - db

volumes:
  pgdata:
